using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Windows.Forms.Design;
using System.Drawing;

using System.Collections;
using System.ComponentModel;
using System.ComponentModel.Design;

namespace pm2_save_editor.CustomControls
{
    abstract class StatContainerBindedComboBox : ComboBox
    {

        // consider having labels autogenerated and autoplaced beside the boxes based on the stat names in the future

        private Stat _bindTarget;
        private StatContainer _boundStat;
        private bool _autoGenerateLabel = true;
        private SmartLabel generatedLabel;

        [Category("Binding"), Description("The stat to which the TextBox should be bound.")]
        public Stat bindTarget
        {
            get
            {
                return _bindTarget;
            }
            set
            {
                _bindTarget = value;
            }
        }

        public void Bind(StatContainer stat)
        {
            _boundStat = stat;
            //this.SelectionChangeCommitted += SelectionUpdated; // should probably add this after the items are added

            if (_autoGenerateLabel)
            {
                GenerateLabel();
            }

        }

        public abstract void AddItems();

        public abstract void SelectionUpdated(object sender, EventArgs e);


        [Category("Binding"), Description("Sets whether or not the TextBox should programatically create its own label.")]
        public bool autoGenerateLabel
        {
            get
            {
                return _autoGenerateLabel;
            }
            set
            {
                _autoGenerateLabel = value;
            }
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.ResumeLayout(false);
        }

        public StatContainerBindedComboBox()
        {
            InitializeComponent();
            this.Visible = false;
        }

        private void GenerateLabel()
        {
            generatedLabel = new SmartLabel();
            generatedLabel.RecalcuateLabelContents(this, _boundStat.GetStatName());
            this.Parent.Controls.Add(generatedLabel);
        }

    }
}
